name: Komodo Core
description: Home-Assistant Addon for Komodo Core
version: '0.12.0'
slug: komodo-core
image: ghcr.io/powerpaul17/image-{arch}-komodo-core
init: false
arch:
  - aarch64
  - amd64
ports:
  9120/tcp: 9120
ingress: true
panel_icon: mdi:server-outline
schema:
  periphery_passkey: password?
  disable_confirm_dialog: bool?
  disable_user_registration: bool?
