name: Semaphore-UI
description: Home-Assistant Addon for Semaphore-UI
version: '0.0.2'
slug: semaphore_ui
init: false
arch:
  - aarch64
  - amd64
  - i386
environment:
  SEMAPHORE_DB_DIALECT: bolt
ingress: true
ingress_port: 3000
panel_icon: mdi:dots-vertical-circle
