name: Semaphore-UI
description: Home-Assistant Addon for Semaphore-UI
version: '0.1.6'
slug: semaphore_ui
image: ghcr.io/powerpaul17/image-{arch}-semaphore-ui
init: false
arch:
  - aarch64
  - amd64
  - i386
ports:
  3000/tcp: 3000
environment:
  SEMAPHORE_CONFIG_PATH: /data/config
  SEMAPHORE_DB_PATH: /data/database
  SEMAPHORE_DB_DIALECT: bolt
  ANSIBLE_HOST_KEY_CHECKING: 'false'
ingress: true
panel_icon: mdi:dots-vertical-circle
hassio_api: true

schema:
  email_enabled: bool?
  email_sender: email?
  email_host: str?
  email_port: port?
  email_username: str?
  email_password: password?
  email_secure: bool?

  slack_enabled: bool?
  slack_url: url?
