name: Semaphore-UI
description: Home-Assistant Addon for Semaphore-UI
version: '0.0.2'
slug: semaphore_ui
init: false
arch:
  - aarch64
  - amd64
  - i386
environment:
  SEMAPHORE_CONFIG_PATH: /data/config
  SEMAPHORE_DB_PATH: /data/database
  SEMAPHORE_DB_DIALECT: bolt
ingress: true
panel_icon: mdi:dots-vertical-circle
