name: Semaphore-UI
description: Home-Assistant Addon for Semaphore-UI
version: '0.0.2'
slug: semaphore_ui
init: false
arch:
  - aarch64
  - amd64
  - i386
ports:
  3000/tcp: 3000
environment:
  SEMAPHORE_CONFIG_PATH: /data/config
  SEMAPHORE_DB_PATH: /data/database
  SEMAPHORE_DB_DIALECT: bolt
  ANSIBLE_HOST_KEY_CHECKING: false
ingress: true
panel_icon: mdi:dots-vertical-circle

options:
  email:
    enabled: false
    port: 25
    secure: false
  slack:
    enabled: false

schema:
  email:
    enabled: bool
    sender: email?
    host: url?
    port: port
    username: str?
    password: password?
    secure: bool
  slack:
    enabled: bool
    url: url?
